import 'shared/styles/globals.css';
import 'shared/styles/variables.css';
import { AlertService } from 'shared/ui/AlertService';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <main>{children}</main>
                <AlertService />
            </body>
        </html>
    );
}
