import 'shared/styles/globals.css';
import 'shared/styles/variables.css';

import { AlertService } from 'shared/ui/AlertService';

import { ReduxProvider } from './providers/ReduxProvider';
import { QueryProvider } from './providers/QueryProvider';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <main>
                    <ReduxProvider>
                        <QueryProvider>{children}</QueryProvider>
                    </ReduxProvider>
                </main>
                <AlertService />
            </body>
        </html>
    );
}
